[package]
name = "stabilize_spirv"
version = "0.0.0"
edition = "2021"

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu", rev = "54f6978" }

[features]
for_qtrhi = []
texture_u32 = []
