name: iOS

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v2
        with:
          key: gf-ios-3
      - name: Dependencies cache
        id: extcache
        uses: actions/cache@v3
        with:
          path: '${{ github.workspace }}/ext/'
          key: ${{ runner.os }}-gf-ext-ios-3

      - name: Force qml-video-rs rebuild (UNIX)
        run: |
          rm -rf ${{ github.workspace }}/target/*/deploy/build/qml-video-rs*
          rm -rf ${{ github.workspace }}/target/deploy/build/qml-video-rs*

      - name: Install Mac certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.MAC_APPSTORE_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}

      - name: Download Provisioning Profiles
        id: provisioning
        uses: apple-actions/download-provisioning-profiles@v2
        with:
          bundle-id: 'xyz.gyroflow'
          profile-type: 'IOS_APP_STORE'
          issuer-id: ${{ secrets.MACOS_ITCONNECT_ISSUER }}
          api-key-id: ${{ secrets.MACOS_ITCONNECT_KEY_ID }}
          api-private-key: ${{ secrets.MACOS_ITCONNECT_KEY }}

      - run: echo ${{ steps.provisioning.outputs.profiles }}

      - uses: extractions/setup-just@v1

      - name: Build Gyroflow (iOS)
        env:
          SIGN_KEY: 7F82D6013B8F6D45F88FE547438744BD64750C5B
          PROVISIONING_PROFILE: /Users/runner/Library/MobileDevice/Provisioning Profiles/${{ fromJSON(steps.provisioning.outputs.profiles)[0].udid }}.mobileprovision
        run: |
          just ios install-deps
          just ios build-ipa

      - name: Upload to App Store
        if: startsWith(github.ref, 'refs/tags/')
        run: xcrun altool --upload-app -f ${{ github.workspace }}/_deployment/_binaries/ios/Gyroflow.ipa -t iOS -u ${{ secrets.MACOS_ACCOUNT_USER }} -p ${{ secrets.MACOS_ACCOUNT_PASS }}

      - name: Save Binaries
        uses: actions/upload-artifact@v3
        with:
          name: Gyroflow-ios
          path: _deployment/_binaries/ios/*.ipa
